# Copyright (c) 2026 Chris Corbyn <chris@zizq.io>
# Licensed under the MIT License. See LICENSE file for details.

# RBS stubs for external gems that don't ship their own RBS declarations.
#
# The type coverage here is intentionally not exhaustive and is simply enough
# for steep to do its static analysis of the Zizq code.

module MessagePack
  def self.pack: (untyped) -> String
  def self.unpack: (String) -> untyped
end

# Async gem — fiber-based concurrency.
module Async
  # Async tasks are generic over some return type that is returned when the
  # task is waited on.
  class Task[out T]
    # Returns the current task if running inside an Async reactor, nil otherwise.
    def self.current?: () -> Task[untyped]?

    # Spawns a new async task that eventually returns the result of the
    # provided block when waited on.
    def async: [U] () { () -> U } -> Task[U]

    # Return the result of the block provided to `#async`
    def wait: () -> T
  end

  class Barrier
    def async: () { () -> void } -> void
    def wait: () -> void
  end

  module HTTP
    class Client
      def initialize: (Endpoint) -> void
      def get: (String, untyped?, ?untyped?) -> untyped
      def post: (String, untyped?, ?untyped?) -> untyped
      def call: (untyped) -> untyped
      def close: () -> void
    end

    class Endpoint
      def self.parse: (String, **untyped) -> Endpoint
    end

    module Protocol
      module HTTP2
      end
    end
  end
end

module Protocol
  module HTTP
    module Body
      module Buffered
        def self.wrap: (String) -> untyped
      end

      class Readable
        include Enumerable[String]
        def each: () { (String) -> void } -> void
        def read: () -> String?
      end
    end

    class Response
      def status: () -> Integer
      def read: () -> String
      def body: () -> Body::Readable
      def close: () -> void
    end
  end
end

module Kernel
  # Top-level `Async { ... }` block, returns a task that eventually returns the
  # result of the block once waited on.
  def Async: [T] () { (Async::Task[T]) -> T } -> Async::Task[T]

  # Top-level `Sync { ... }` block, creates a fiber scheduler if needed.
  def Sync: [T] () { () -> T } -> T
end
